include:
  - 'https://gitlab.esss.lu.se/ics-infrastructure/gitlab-ci-yml/raw/master/PreCommit.gitlab-ci.yml'
  - 'https://gitlab.esss.lu.se/ics-infrastructure/gitlab-ci-yml/raw/master/ArtifactoryPyPI.gitlab-ci.yml'

.runner_tags: &runner_tags
  tags:
    - docker

variables:
  PIP_INDEX_URL: "https://artifactory.esss.lu.se/artifactory/api/pypi/pypi-virtual/simple"

stages:
  - check
  - build
  - test
  - release

test-python36:
  <<: *runner_tags
  stage: test
  image: registry.esss.lu.se/ics-docker/miniconda
  before_script:
    - source /etc/profile.d/conda.sh
    - conda create -n iocsh -y -c conda-e3-virtual python=3.6 iocstats=3.1.16
    - conda activate iocsh
    - pip install pytest
    - pip install -e .
  script:
    - run-iocsh -h
    - pytest -v tests

test-python37:
  <<: *runner_tags
  stage: test
  image: registry.esss.lu.se/ics-docker/miniconda
  before_script:
    - source /etc/profile.d/conda.sh
    - conda create -n iocsh -y -c conda-e3-virtual python=3.7 iocstats=3.1.16
    - conda activate iocsh
    - pip install pytest
    - pip install -e .
  script:
    - run-iocsh -h
    - pytest -v tests
