[metadata]
name = run-iocsh
version = 0.8.5
description = Wrapper to test iocsh
long_description = file: README.rst
long_description_content_type = text/x-rst
url = https://gitlab.esss.lu.se/ics-infrastructure/run-iocsh
author = Benjamin Bertrand
maintainer = Anders Lindh Olsson
maintainer_email = anders.lindh.olsson@ess.eu
license = BSD-2 license
keywords = iocsh, e3, epics, ess
classifiers =
  Development Status :: 3 - Alpha
  Intended Audience :: Developers
  License :: OSI Approved :: BSD-2 License
  Programming Language :: Python :: 3 :: Only
  Programming Language :: Python :: 3.6
  Programming Language :: Python :: 3.7

[options]
zip_safe = False
packages = find:
include_package_data = True
python_requires = >=3.6
setup_requires =
  wheel

[options.extras_require]
dev =
  pytest
  pytest-cov
  pyepics
  pvapy
  p4p

[options.entry_points]
console_scripts =
  run-iocsh = run_iocsh.cli:main
