sonar.organization=epics-extensions
sonar.projectKey=epics-extensions_run-iocsh
sonar.projectName=run-iocsh

sonar.sources=run_iocsh
sonar.tests=tests
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
